default_platform :ios

platform :ios do
  before_all do
  end

  desc "register a device on apple dev portal"
  lane :register_device do |options|
    register_devices(
      devices: {
        options[:name] => options[:udid]
      },
      username: options[:username]
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
    puts "#{exception} caused by #{lane}"
    sh "exit 1"
  end
end